# Global Settings
keep_files: [.git, README.md]

# Site settings
title: Awesome Omniverse
email: jacortesmahmud@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my website blog about web technologies like Javascript, HTML5, CSS and also
  about entertainment content of my own interest, so keep it cool and stay awesome!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jcortes.github.io" # the base hostname & protocol for your site
github_username:  jcortes

# Build settings
markdown: kramdown
